DrawAndGuessV3/Models/Point.cs
namespace DrawAndGuessV3.Models
{
    public class Point {
        public int X { get; set; }
        public int Y { get; set; }
    }
}

DrawAndGuessV3/Models/Stroke.cs
namespace DrawAndGuessV3.Models
{
    public class Stroke
    {
        public Point? Start { get; set; }
        public Point? End { get; set; }
        public string? Color { get; set; }
    }
}

DrawAndGuessV3/Models/User.cs
namespace DrawAndGuessV3.Models
{
    public class User
    {
        public string? ConnectionId { get; set; }
        public string? Name { get; set; }
    }
}

DrawAndGuessV3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DrawAndGuessV3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DrawAndGuessV3/Pages/Game.cshtml.cs
using DrawAndGuessV3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DrawAndGuessV3.Pages
{
    public class GameModel : PageModel
    {
        public void OnPost()
        {
        }
        public void OnGet()
        {
        }
    }
}

DrawAndGuessV3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DrawAndGuessV3.Models;
using DrawAndGuessV3.Modules;
using System;

namespace DrawAndGuessV3.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnPostSetName()
        {
            // If name is empty, return to main page
            if (string.IsNullOrEmpty(Request.Form["name"]))
                return Redirect("Index");
            
            // else redirect to game page
            HttpContext.Session.SetString("name", Request.Form["name"]);
            return Redirect("Game");
        }
    }
}

DrawAndGuessV3/Pages/Game.cshtml
@page
@model DrawAndGuessV3.Pages.GameModel
@{
    if (HttpContext.Session.GetString("name") == null)
    {
        Response.Redirect("/");
    }

    ViewData["Title"] = "Game";
}
<div id="hero2" class="grid-container">
    <p hidden id="name">@HttpContext.Session.GetString("name")</p>
    <div id='bodybox2'>
        <div id='chatborder2'>
        @* <p id="status" style="color:white; font-size:15px; text-align:center">Remains: <span id="time">60</span> sec</p><hr> *@
        <p id="status" style="color:white; font-size:15px; text-align:center">Waiting for users...</p><hr>
        <ol id="players">
        </ol>
        </div>
    </div>
    <div class="paintbox">
        <div>
            <input type="color" id="color" class="colorbtn" value="#000000" />
            <input type="button" id="clear" class="btn-primary clearbtn" value="Clear" />
        </div>
        <div>
            <canvas id="draw-canvas" height="584" width="800"></canvas>
        </div>
    </div>
    <div id='bodybox'>
        <div id='chatborder'>
          <p id="chatlog13" class="chatlog">&nbsp;</p>
          <p id="chatlog12" class="chatlog">&nbsp;</p>
          <p id="chatlog11" class="chatlog">&nbsp;</p>
          <p id="chatlog10" class="chatlog">&nbsp;</p>
          <p id="chatlog9" class="chatlog">&nbsp;</p>
          <p id="chatlog8" class="chatlog">&nbsp;</p>
          <p id="chatlog7" class="chatlog">&nbsp;</p>
          <p id="chatlog6" class="chatlog">&nbsp;</p>
          <p id="chatlog5" class="chatlog">&nbsp;</p>
          <p id="chatlog4" class="chatlog">&nbsp;</p>
          <p id="chatlog3" class="chatlog">&nbsp;</p>
          <p id="chatlog2" class="chatlog">&nbsp;</p>
          <p id="chatlog1" class="chatlog">&nbsp;</p>
          
          <input type="text" name="chat" id="chatbox" placeholder="Type your guess here..." maxlength="20">  
        </div>
    </div>
</div>

<script src="https://unpkg.com/@@aspnet/signalr@@1.0.0/dist/browser/signalr.js"></script>
<script src="js/draw.js"></script>
<script src="js/chat.js"></script>
<script src="js/user.js"></script>

DrawAndGuessV3/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<section id="hero" class='animate__animated animate__fadeIn animate__slow '>
      <div>
        <h1 id="drawnguess">DRAW & GUESS</h1>
        <form method="post" asp-page-handler="SetName">
          <input name="Name" class="input-get-started" placeholder='Enter your name' maxlength="12"><br>
          <button class="btn-hover color-1" type="submit" value="Play">PLAY!</button>
        </form>
      </div>

      <h3 onclick="view('about'); " id="h31" >About</h3>
      <div id="about" style="display: none;" class="animate__animated animate__fadeIn ">
        <p class="blocktext">Draw&Guess - the name speaks itself, it is a free multiplayer drawing and guessing game.
          One game consists of a few rounds in which every round someone has to draw their chosen word and others have to guess it to gain points!
          The person with the most points at the end of game will then be crowned as the winner!</p>
      </div>

      <h3 onclick="view('rules'); " id="h32" >Rules</h3>
      <div id="rules" style="display: none;" class="animate__animated animate__fadeIn">
        <p class="blocktext">When its your turn to draw, you will have to choose a word from three options and visualize that word in 60 seconds,
          alternatively when somebody else is drawing you have to type your guess into the chat to gain points,
          be quick, the earlier you guess a word the more points you get!</p>
      </div>
</section>

DrawAndGuessV3/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" />
    <link rel="icon" href="~/images/icons/favicon.png" />
    <link rel="apple-touch-icon" href="~/images/icons/apple-touch-icon.png" />

    <!-- CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DrawAndGuessV3.styles.css" asp-append-version="true" />

    <!-- Animations CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

    <!-- Title -->
    <title>Draw & Guess</title>
</head>
<body onload="changeBg()">
    <section>
        <header>
            <nav class="navbar containerc">
                <a asp-area="" asp-page="/Index"><img src='images/icons/logo.png' class="logo logoplus" ></a>
                <input type="checkbox" id="toggler">
                <label for="toggler"><i class="ri-menu-line"></i></label>
            </nav>
        </header>
    </section>

    <div class="containerc">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <section id="basic-footer" class="sectionfooter">
            <div class="footer-basic">
                <footer>
                    <div class="social">
                        <a href="https://www.instagram.com/a2b_projects/"><i class="icon ion-social-instagram"></i></a>
                        <a href="https://www.funcage.com/"><i class="icon ion-social-snapchat"></i></a>
                        <a href="https://www.facebook.com/groups/442518676508064"><i class="icon ion-social-facebook"></i></a>
                    </div>
                    <p class="copyright">The owner of this site is not responsible for any user generated content (drawings, messages, usernames)</p>
                    <p class="copyright">! Current version is not compatible with mobile devices !</p>
                    <a href="terms.html">
                        <p class="copyright">Terms of Service</p>
                    </a>
                    <p class="copyright">WhileTrue © 2022</p>
                </footer>
            </div>
        </section>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>